import { canvasFont, scalePixels } from "../../core/utils";
import { BASE_CONSTANTS } from "../base";

const GLOBAL_SCALE = BASE_CONSTANTS.GLOBAL_SCALE;

export const FISHING_CONSTANTS = {
  CAST_DURATION: 0.45,
  BITE_DELAY_MIN: 2.1,
  BITE_DELAY_MAX: 6.4,
  BITE_WINDOW: 1.3,
  RESULT_DURATION: 1.1,
  TENSION_SNAP: 1,
  PROGRESS_TARGET: 1,
  PROGRESS_GAIN: 0.55,
  PROGRESS_DECAY: 0.15,
  TENSION_GAIN: 0.92,
  TENSION_RELEASE: 1.08,
  PULL_WAVE: 0.2,
  PULL_BURST_DRAIN: 0.65,
  PULL_BURST_CHANCE: 0.45,
  PULL_BURST_MIN: 0.22,
  PULL_BURST_MAX: 0.42,
  BOBBER_HIT_RADIUS: scalePixels(10, GLOBAL_SCALE),
  BOBBER_VISUAL_RADIUS: scalePixels(4, GLOBAL_SCALE),
  CAST_ARC_HEIGHT: scalePixels(18, GLOBAL_SCALE),
  BOBBER_SWAY_X: 1.1 * GLOBAL_SCALE,
  BOBBER_SWAY_Y: 0.9 * GLOBAL_SCALE,
  BOBBER_BITE_DIP_BASE: 2 * GLOBAL_SCALE,
  BOBBER_BITE_DIP_WAVE: 2.1 * GLOBAL_SCALE,
  BOBBER_PULSE_BASE: scalePixels(7, GLOBAL_SCALE),
  BOBBER_PULSE_WAVE: 1.5 * GLOBAL_SCALE,
  LINE_WIDTH: 1.5 * GLOBAL_SCALE,
  HUD_TEXT_FONT: canvasFont(12, GLOBAL_SCALE),
  HUD_META_FONT: canvasFont(11, GLOBAL_SCALE),
} as const;
