import type { RecipeStub } from "./types";

export const MOCK_RECIPES: RecipeStub[] = [
  {
    id: "pan-fried-whitefish",
    name: "Pan-Fried Whitefish",
    cookTimeMinutes: 18,
    requiredFishName: "Whitefish",
    requiredFishScientificName: null,
    currentFishQuantity: 1,
    requiredFishQuantity: 1,
    rarity: "common",
    estimatedPrice: 12,
    craftCost: 2.4,
    calories: 420,
    instructions: null,
    hasRequiredFish: true,
    canAfford: true,
    isCraftable: true,
    missingRequiredFishCount: 0,
    missingBalanceAmount: 0,
    availabilityLabel: "Ready to cook",
    summary: "A placeholder recipe used only for development.",
    dishTypes: ["main course"],
    cuisines: ["Coastal"],
    diets: ["pescatarian"],
    servingsLabel: "Servings: 2",
    nutritionLines: ["Calories: 420"],
    ingredients: [{ text: "1 Whitefish fillet", isRequiredFishIngredient: true }],
  },
];
