export const RECIPES_PER_COLUMN = 4;
export const RECIPE_COLUMNS_PER_SPREAD = 2;
export const RECIPES_PER_SPREAD = RECIPES_PER_COLUMN * RECIPE_COLUMNS_PER_SPREAD;
export const WORKSTATION_INTERACT_TILE_DISTANCE = 1;
