export const RECIPES_PER_COLUMN = 6;
export const RECIPE_COLUMNS_PER_SPREAD = 1;
export const RECIPES_PER_SPREAD = RECIPES_PER_COLUMN * RECIPE_COLUMNS_PER_SPREAD;
export const WORKSTATION_INTERACT_TILE_DISTANCE = 1;
