import type { PlaceholderFishDefinition } from "./types";

export const PLACEHOLDER_FISH_CATALOG: PlaceholderFishDefinition[] = [
  {
    id: "sunstripe-snapper",
    name: "Sunstripe Snapper",
    scientificName: "Snapperus aurora",
    region: "Coral Shelf",
    rarity: "Common",
    value: 14,
    placeholderVisual: "SNP",
  },
  {
    id: "mist-fin-cod",
    name: "Mistfin Cod",
    scientificName: "Codus nebula",
    region: "North Shoals",
    rarity: "Common",
    value: 16,
    placeholderVisual: "COD",
  },
  {
    id: "ember-tail-perch",
    name: "Embertail Perch",
    scientificName: "Perca ignita",
    region: "Drift Reefs",
    rarity: "Common",
    value: 13,
    placeholderVisual: "PER",
  },
  {
    id: "moon-reef-bream",
    name: "Moonreef Bream",
    scientificName: "Breama lunis",
    region: "Moonlit Bay",
    rarity: "Uncommon",
    value: 23,
    placeholderVisual: "BRM",
  },
  {
    id: "kelpback-bass",
    name: "Kelpback Bass",
    scientificName: "Bassarum fronde",
    region: "Kelp Groves",
    rarity: "Uncommon",
    value: 25,
    placeholderVisual: "BAS",
  },
  {
    id: "jade-raylet",
    name: "Jade Raylet",
    scientificName: "Raya viridis",
    region: "Tide Flats",
    rarity: "Uncommon",
    value: 27,
    placeholderVisual: "RAY",
  },
  {
    id: "storm-glass-eel",
    name: "Stormglass Eel",
    scientificName: "Aquila vitreus",
    region: "Tempest Channel",
    rarity: "Rare",
    value: 41,
    placeholderVisual: "EEL",
  },
  {
    id: "frost-gill-trout",
    name: "Frostgill Trout",
    scientificName: "Trutta glacies",
    region: "Cold Current",
    rarity: "Rare",
    value: 44,
    placeholderVisual: "TRT",
  },
  {
    id: "ruby-lantern-koi",
    name: "Ruby Lantern Koi",
    scientificName: "Koius rubra",
    region: "Deep Lantern Pool",
    rarity: "Rare",
    value: 48,
    placeholderVisual: "KOI",
  },
  {
    id: "crownfin-oracle",
    name: "Crownfin Oracle",
    scientificName: "Regalis mira",
    region: "Whisper Trench",
    rarity: "Legendary",
    value: 72,
    placeholderVisual: "CRN",
  },
];
